### PR TITLE
Add minimatch based testPattern support

### PR DESCRIPTION
**Pull request by mmlb**

### CODE REVIEW

**Comment by mmlb** [comment]
So far just an initial commit to see if I'm doing anything right at all :D

**Comment by maks-rafalko** [comment]
Cool. Would you mind updating the `README.md` as well to document this new feature?

**Comment by mmlb** [comment]
Oops, yes of course!

**Comment by mmlb** [comment]
@maks-rafalko updated. I also tweaked/cleaned up the README.md a little bit, let me know if you don't like the "one-sentence-per-line" thing and I will remove it.

**Comment by maks-rafalko** [comment]
Thank you @mmlb for this contribution!

Merging it. I will post when it's deployed (I think I will be able to do it by the end of the week).

Feel free to ping me if it won't be the case.

**Comment by maks-rafalko** [comment]
It has been deployed.

Please test it when you have a chance. Thank you!

**Pull request merged**
